package constants;

@:enum abstract Obj(Int) from Int to Int{
    public var NO_OBJ = -1;
    public var ALTAR_OF_SACRIFICE = 2;
    public var ANCHOR_POINT = 3;
    public var ARENA = 4;
    public var ARTIFACT = 5;
    public var PANDORAS_BOX = 6;
    public var BLACK_MARKET = 7;
    public var BOAT = 8;
    public var BORDERGUARD = 9;
    public var KEYMASTER = 10;
    public var BUOY = 11;
    public var CAMPFIRE = 12;
    public var CARTOGRAPHER = 13;
    public var SWAN_POND = 14;
    public var COVER_OF_DARKNESS = 15;
    public var CREATURE_BANK = 16;
    public var CREATURE_GENERATOR1 = 17;
    public var CREATURE_GENERATOR2 = 18;
    public var CREATURE_GENERATOR3 = 19;
    public var CREATURE_GENERATOR4 = 20;
    public var CURSED_GROUND1 = 21;
    public var CORPSE = 22;
    public var MARLETTO_TOWER = 23;
    public var DERELICT_SHIP = 24;
    public var DRAGON_UTOPIA = 25;
    public var EVENT = 26;
    public var EYE_OF_MAGI = 27;
    public var FAERIE_RING = 28;
    public var FLOTSAM = 29;
    public var FOUNTAIN_OF_FORTUNE = 30;
    public var FOUNTAIN_OF_YOUTH = 31;
    public var GARDEN_OF_REVELATION = 32;
    public var GARRISON = 33;
    public var HERO = 34;
    public var HILL_FORT = 35;
    public var GRAIL = 36;
    public var HUT_OF_MAGI = 37;
    public var IDOL_OF_FORTUNE = 38;
    public var LEAN_TO = 39;
    public var LIBRARY_OF_ENLIGHTENMENT = 41;
    public var LIGHTHOUSE = 42;
    public var MONOLITH_ONE_WAY_ENTRANCE = 43;
    public var MONOLITH_ONE_WAY_EXIT = 44;
    public var MONOLITH_TWO_WAY = 45;
    public var MAGIC_PLAINS1 = 46;
    public var SCHOOL_OF_MAGIC = 47;
    public var MAGIC_SPRING = 48;
    public var MAGIC_WELL = 49;
    public var MERCENARY_CAMP = 51;
    public var MERMAID = 52;
    public var MINE = 53;
    public var MONSTER = 54;
    public var MYSTICAL_GARDEN = 55;
    public var OASIS = 56;
    public var OBELISK = 57;
    public var REDWOOD_OBSERVATORY = 58;
    public var OCEAN_BOTTLE = 59;
    public var PILLAR_OF_FIRE = 60;
    public var STAR_AXIS = 61;
    public var PRISON = 62;
    public var PYRAMID = 63;//subtype 0
    public var WOG_OBJECT = 63;//subtype > 0
    public var RALLY_FLAG = 64;
    public var RANDOM_ART = 65;
    public var RANDOM_TREASURE_ART = 66;
    public var RANDOM_MINOR_ART = 67;
    public var RANDOM_MAJOR_ART = 68;
    public var RANDOM_RELIC_ART = 69;
    public var RANDOM_HERO = 70;
    public var RANDOM_MONSTER = 71;
    public var RANDOM_MONSTER_L1 = 72;
    public var RANDOM_MONSTER_L2 = 73;
    public var RANDOM_MONSTER_L3 = 74;
    public var RANDOM_MONSTER_L4 = 75;
    public var RANDOM_RESOURCE = 76;
    public var RANDOM_TOWN = 77;
    public var REFUGEE_CAMP = 78;
    public var RESOURCE = 79;
    public var SANCTUARY = 80;
    public var SCHOLAR = 81;
    public var SEA_CHEST = 82;
    public var SEER_HUT = 83;
    public var CRYPT = 84;
    public var SHIPWRECK = 85;
    public var SHIPWRECK_SURVIVOR = 86;
    public var SHIPYARD = 87;
    public var SHRINE_OF_MAGIC_INCANTATION = 88;
    public var SHRINE_OF_MAGIC_GESTURE = 89;
    public var SHRINE_OF_MAGIC_THOUGHT = 90;
    public var SIGN = 91;
    public var SIRENS = 92;
    public var SPELL_SCROLL = 93;
    public var STABLES = 94;
    public var TAVERN = 95;
    public var TEMPLE = 96;
    public var DEN_OF_THIEVES = 97;
    public var TOWN = 98;
    public var TRADING_POST = 99;
    public var LEARNING_STONE = 100;
    public var TREASURE_CHEST = 101;
    public var TREE_OF_KNOWLEDGE = 102;
    public var SUBTERRANEAN_GATE = 103;
    public var UNIVERSITY = 104;
    public var WAGON = 105;
    public var WAR_MACHINE_FACTORY = 106;
    public var SCHOOL_OF_WAR = 107;
    public var WARRIORS_TOMB = 108;
    public var WATER_WHEEL = 109;
    public var WATERING_HOLE = 110;
    public var WHIRLPOOL = 111;
    public var WINDMILL = 112;
    public var WITCH_HUT = 113;
    public var HOLE = 124;
    public var RANDOM_MONSTER_L5 = 162;
    public var RANDOM_MONSTER_L6 = 163;
    public var RANDOM_MONSTER_L7 = 164;
    public var BORDER_GATE = 212;
    public var FREELANCERS_GUILD = 213;
    public var HERO_PLACEHOLDER = 214;
    public var QUEST_GUARD = 215;
    public var RANDOM_DWELLING = 216;
    public var RANDOM_DWELLING_LVL = 217; //subtype = creature level
    public var RANDOM_DWELLING_FACTION = 218; //subtype = faction
    public var GARRISON2 = 219;
    public var ABANDONED_MINE = 220;
    public var TRADING_POST_SNOW = 221;
    public var CLOVER_FIELD = 222;
    public var CURSED_GROUND2 = 223;
    public var EVIL_FOG = 224;
    public var FAVORABLE_WINDS = 225;
    public var FIERY_FIELDS = 226;
    public var HOLY_GROUNDS = 227;
    public var LUCID_POOLS = 228;
    public var MAGIC_CLOUDS = 229;
    public var MAGIC_PLAINS2 = 230;
    public var ROCKLANDS = 231;

    public function toString():String {
        return switch(this) {
            case NO_OBJ: "NO_OBJ";
            case ALTAR_OF_SACRIFICE: "ALTAR_OF_SACRIFICE";
            case ANCHOR_POINT: "ANCHOR_POINT";
            case ARENA: "ARENA";
            case ARTIFACT: "ARTIFACT";
            case PANDORAS_BOX: "PANDORAS_BOX";
            case BLACK_MARKET: "BLACK_MARKET";
            case BOAT: "BOAT";
            case BORDERGUARD: "BORDERGUARD";
            case KEYMASTER: "KEYMASTER";
            case BUOY: "BUOY";
            case CAMPFIRE: "CAMPFIRE";
            case CARTOGRAPHER: "CARTOGRAPHER";
            case SWAN_POND: "SWAN_POND";
            case COVER_OF_DARKNESS: "COVER_OF_DARKNESS";
            case CREATURE_BANK: "CREATURE_BANK";
            case CREATURE_GENERATOR1: "CREATURE_GENERATOR1";
            case CREATURE_GENERATOR2: "CREATURE_GENERATOR2";
            case CREATURE_GENERATOR3: "CREATURE_GENERATOR3";
            case CREATURE_GENERATOR4: "CREATURE_GENERATOR4";
            case CURSED_GROUND1: "CURSED_GROUND1";
            case CORPSE: "CORPSE";
            case MARLETTO_TOWER: "MARLETTO_TOWER";
            case DERELICT_SHIP: "DERELICT_SHIP";
            case DRAGON_UTOPIA: "DRAGON_UTOPIA";
            case EVENT: "EVENT";
            case EYE_OF_MAGI: "EYE_OF_MAGI";
            case FAERIE_RING: "FAERIE_RING";
            case FLOTSAM: "FLOTSAM";
            case FOUNTAIN_OF_FORTUNE: "FOUNTAIN_OF_FORTUNE";
            case FOUNTAIN_OF_YOUTH: "FOUNTAIN_OF_YOUTH";
            case GARDEN_OF_REVELATION: "GARDEN_OF_REVELATION";
            case GARRISON: "GARRISON";
            case HERO: "HERO";
            case HILL_FORT: "HILL_FORT";
            case GRAIL: "GRAIL";
            case HUT_OF_MAGI: "HUT_OF_MAGI";
            case IDOL_OF_FORTUNE: "IDOL_OF_FORTUNE";
            case LEAN_TO: "LEAN_TO";
            case LIBRARY_OF_ENLIGHTENMENT: "LIBRARY_OF_ENLIGHTENMENT";
            case LIGHTHOUSE: "LIGHTHOUSE";
            case MONOLITH_ONE_WAY_ENTRANCE: "MONOLITH_ONE_WAY_ENTRANCE";
            case MONOLITH_ONE_WAY_EXIT: "MONOLITH_ONE_WAY_EXIT";
            case MONOLITH_TWO_WAY: "MONOLITH_TWO_WAY";
            case MAGIC_PLAINS1: "MAGIC_PLAINS1";
            case SCHOOL_OF_MAGIC: "SCHOOL_OF_MAGIC";
            case MAGIC_SPRING: "MAGIC_SPRING";
            case MAGIC_WELL: "MAGIC_WELL";
            case MERCENARY_CAMP: "MERCENARY_CAMP";
            case MERMAID: "MERMAID";
            case MINE: "MINE";
            case MONSTER: "MONSTER";
            case MYSTICAL_GARDEN: "MYSTICAL_GARDEN";
            case OASIS: "OASIS";
            case OBELISK: "OBELISK";
            case REDWOOD_OBSERVATORY: "REDWOOD_OBSERVATORY";
            case OCEAN_BOTTLE: "OCEAN_BOTTLE";
            case PILLAR_OF_FIRE: "PILLAR_OF_FIRE";
            case STAR_AXIS: "STAR_AXIS";
            case PRISON: "PRISON";
            case PYRAMID: "PYRAMID";
            case WOG_OBJECT: "WOG_OBJECT";
            case RALLY_FLAG: "RALLY_FLAG";
            case RANDOM_ART: "RANDOM_ART";
            case RANDOM_TREASURE_ART: "RANDOM_TREASURE_ART";
            case RANDOM_MINOR_ART: "RANDOM_MINOR_ART";
            case RANDOM_MAJOR_ART: "RANDOM_MAJOR_ART";
            case RANDOM_RELIC_ART: "RANDOM_RELIC_ART";
            case RANDOM_HERO: "RANDOM_HERO";
            case RANDOM_MONSTER: "RANDOM_MONSTER";
            case RANDOM_MONSTER_L1: "RANDOM_MONSTER_L1";
            case RANDOM_MONSTER_L2: "RANDOM_MONSTER_L2";
            case RANDOM_MONSTER_L3: "RANDOM_MONSTER_L3";
            case RANDOM_MONSTER_L4: "RANDOM_MONSTER_L4";
            case RANDOM_RESOURCE: "RANDOM_RESOURCE";
            case RANDOM_TOWN: "RANDOM_TOWN";
            case REFUGEE_CAMP: "REFUGEE_CAMP";
            case RESOURCE: "RESOURCE";
            case SANCTUARY: "SANCTUARY";
            case SCHOLAR: "SCHOLAR";
            case SEA_CHEST: "SEA_CHEST";
            case SEER_HUT: "SEER_HUT";
            case CRYPT: "CRYPT";
            case SHIPWRECK: "SHIPWRECK";
            case SHIPWRECK_SURVIVOR: "SHIPWRECK_SURVIVOR";
            case SHIPYARD: "SHIPYARD";
            case SHRINE_OF_MAGIC_INCANTATION: "SHRINE_OF_MAGIC_INCANTATION";
            case SHRINE_OF_MAGIC_GESTURE: "SHRINE_OF_MAGIC_GESTURE";
            case SHRINE_OF_MAGIC_THOUGHT: "SHRINE_OF_MAGIC_THOUGHT";
            case SIGN: "SIGN";
            case SIRENS: "SIRENS";
            case SPELL_SCROLL: "SPELL_SCROLL";
            case STABLES: "STABLES";
            case TAVERN: "TAVERN";
            case TEMPLE: "TEMPLE";
            case DEN_OF_THIEVES: "DEN_OF_THIEVES";
            case TOWN: "TOWN";
            case TRADING_POST: "TRADING_POST";
            case LEARNING_STONE: "LEARNING_STONE";
            case TREASURE_CHEST: "TREASURE_CHEST";
            case TREE_OF_KNOWLEDGE: "TREE_OF_KNOWLEDGE";
            case SUBTERRANEAN_GATE: "SUBTERRANEAN_GATE";
            case UNIVERSITY: "UNIVERSITY";
            case WAGON: "WAGON";
            case WAR_MACHINE_FACTORY: "WAR_MACHINE_FACTORY";
            case SCHOOL_OF_WAR: "SCHOOL_OF_WAR";
            case WARRIORS_TOMB: "WARRIORS_TOMB";
            case WATER_WHEEL: "WATER_WHEEL";
            case WATERING_HOLE: "WATERING_HOLE";
            case WHIRLPOOL: "WHIRLPOOL";
            case WINDMILL: "WINDMILL";
            case WITCH_HUT: "WITCH_HUT";
            case HOLE: "HOLE";
            case RANDOM_MONSTER_L5: "RANDOM_MONSTER_L5";
            case RANDOM_MONSTER_L6: "RANDOM_MONSTER_L6";
            case RANDOM_MONSTER_L7: "RANDOM_MONSTER_L7";
            case BORDER_GATE: "BORDER_GATE";
            case FREELANCERS_GUILD: "FREELANCERS_GUILD";
            case HERO_PLACEHOLDER: "HERO_PLACEHOLDER";
            case QUEST_GUARD: "QUEST_GUARD";
            case RANDOM_DWELLING: "RANDOM_DWELLING";
            case RANDOM_DWELLING_LVL: "RANDOM_DWELLING_LVL";
            case RANDOM_DWELLING_FACTION: "RANDOM_DWELLING_FACTION";
            case GARRISON2: "GARRISON2";
            case ABANDONED_MINE: "ABANDONED_MINE";
            case TRADING_POST_SNOW: "TRADING_POST_SNOW";
            case CLOVER_FIELD: "CLOVER_FIELD";
            case CURSED_GROUND2: "CURSED_GROUND2";
            case EVIL_FOG: "EVIL_FOG";
            case FAVORABLE_WINDS: "FAVORABLE_WINDS";
            case FIERY_FIELDS: "FIERY_FIELDS";
            case HOLY_GROUNDS: "HOLY_GROUNDS";
            case LUCID_POOLS: "LUCID_POOLS";
            case MAGIC_CLOUDS: "MAGIC_CLOUDS";
            case MAGIC_PLAINS2: "MAGIC_PLAINS2";
            case ROCKLANDS: "ROCKLANDS";
            default: "NONE";
        }
    }
}
